export const Features =
    [
        {name: "pickup", value: "Pickup"},
        {name: "delivery", value: "Delivery"},
        {name: "reservations", value: "Reservations"},
        {name: "hotDogs", value: "Hot dogs"},
        {name: "pizza", value: "Pizza"},
        {name: "traditionalAmerican", value: "Traditional American"},
        {name: "sandwiches", value: "Sandwiches"},
        {name: "burgers", value: "Burgers"},
        {name: "coffee", value: "Coffee"},
        {name: "mexican", value: "Mexican"},
        {name: "brunch", value: "Brunch"},
        {name: "newAmerican", value: "New American"},
        {name: "italian", value: "Italian"},
        {name: "chinese", value: "Chinese"},
        {name: "bar", value: "Bar"},
        {name: "sportsBar", value: "Sports Bar"},
        {name: "chickenWings", value: "Chicken wings"},
        {name: "iceCream", value: "Ice cream"},
        {name: "seafood", value: "Seafood"},
        {name: "bakery", value: "Bakeries"},
        {name: "salad", value: "Salad"},
        {name: "desserts", value: "Desserts"},
        {name: "delis", value: "Delis"},
        {name: "japanese", value: "Japanese"},
        {name: "bbq", value: "Bbq"},
        {name: "juiceBars", value: "Juice bar"},
        {name: "cafes", value: "Cafe"},
        {name: "mediterranean", value: "Mediterranean"},
        {name: "steak", value: "Steak"},
        {name: "asianFusion", value: "Asian Fusion"},
        {name: "vegetarian", value: "Vegetarian"},
        {name: "vegan", value: "Vegan"},
        {name: "price", value: "Price"},
        {name: "rating", value: "Rating"},
    ]
