export const Features =
    [
        // "rating",
        // "price",
        "pickup",
        "delivery",
        "reservations",
        // "total_restaurants_zip",
        // "Total_Reviews_Zip",
        // "Average_Rating_Zip",
        // "Average_Price_Zip",
        "hot dogs",
        "pizza",
        "traditional american",
        "sandwiches",
        "burgers",
        "coffee",
        "mexican",
        "brunch",
        "new american",
        "italian",
        "chinese",
        "bars",
        "chicken wings",
        "ice cream",
        "seafood",
        "sports bars",
        "bakeries",
        "salad",
        "desserts",
        "delis",
        "japanese",
        "bbq",
        "juice bars",
        "cafes",
        "mediterranean",
        "steak",
        "asian fusion",
        "vegetarian",
        "vegan",
        // "business_ratio",
        // "Rural_urban_continuum_code_2013",
        // "Metro_2013",
        // "Unemployment_rate_2020",
        // "covid_high",
        // "covid_low",
        // "covid_moderate",
        // "SizeRank",
        // "zillow_sfh_sale_price",
        // "is_closed"
    ]
